##
# V1
##

PassEnv REPO_ROOT
PassEnv APP_URL

# Docker root folder is /var/www/html see under: 
# Configuring apache: https://hub.docker.com/r/microsoft/devcontainers-php#starting--stopping-apache
Define DOCUMENTROOT /var/www/html

DocumentRoot ${DOCUMENTROOT}
ServerName ${APP_URL}

# Configure Logging
# Note: use the absolute path to rotatelogs or you will get an error:
#(2)No such file or directory: AH00089: Couldn't start ErrorLog process 'rotatelogs -f -t -c /var/log/apache2/ffspud-error.log 1M'.
#
#LogFormat "%h %l %u %t \"%r\" %>s %b" common
#CustomLog "|/usr/bin/rotatelogs -f -t -c ${APACHE_LOG_DIR}/dev-access.log 1M" common
#ErrorLog  "|/usr/bin/rotatelogs -f -t -c ${APACHE_LOG_DIR}/dev-error.log 1M"
#TransferLog ${APACHE_LOG_DIR}/transfer.log

### Laravel static resources
Alias /vendor/ "${REPO_ROOT}/laravel/public/vendor/"
<Directory "${REPO_ROOT}/laravel/public/vendor/">
    Require all granted
</Directory>

Alias /dist/ "${REPO_ROOT}/laravel/public/dist/"
<Directory "${REPO_ROOT}/laravel/public/dist/">
    Require all granted
</Directory>

Alias /storage/ "${REPO_ROOT}/laravel/public/storage/"
<Directory "${REPO_ROOT}/laravel/public/storage/">
    Options +FollowSymLinks
    Require all granted
</Directory>


<Directory "${DOCUMENTROOT}">

    #php.ini settings
    php_value memory_limit        400M
    php_value upload_max_filesize 60M
    php_value post_max_size       62M
    php_value max_execution_time  1800
    
    Options +Indexes
	Options FollowSymLinks
    AllowOverride all
	Require all granted
</Directory>
